image: microsoft/dotnet:latest

stages:
    - build

variables:
    test: "Exemple.Test"

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:    
    stage: test   
    script: 
       -"cd $test" 
       -"dotnet test"