//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMOUNT_OF_INCREASE
    {
        public int ID { get; set; }
        public Nullable<int> CURRENCY_ID { get; set; }
        public Nullable<decimal> MAX_PRICE { get; set; }
        public Nullable<decimal> MIN_PRICE { get; set; }
        public Nullable<decimal> INCREASE_PRICE { get; set; }
        public Nullable<System.DateTime> DATE_OF_UPDATE { get; set; }
        public Nullable<int> UPDATED_PERSON_ID { get; set; }
    }
}
