//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class auction
    {
        public int ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<System.DateTime> ACUTION_DATE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> ACUTION_SALES_TIME { get; set; }
        public Nullable<int> AMOUNT_OF_INCREASE_ID { get; set; }
        public Nullable<System.DateTime> DATE_OF_UPDATE { get; set; }
        public Nullable<int> UPDATED_PERSON_ID { get; set; }
    }
}
