//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        public int CarDetailId { get; set; }
        public Nullable<int> CarTechnicalId { get; set; }
        public Nullable<int> CarHardwareId { get; set; }
    }
}
