//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTechnicalDetail
    {
        public int CarTechnicalDetailId { get; set; }
        public Nullable<int> CarMakeId { get; set; }
        public Nullable<int> GearTypeId { get; set; }
        public Nullable<int> EngineDisplacement { get; set; }
        public Nullable<int> Mileage { get; set; }
        public string LicancePlate { get; set; }
        public Nullable<int> FuelType_Id { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
        public string CarVersion { get; set; }
        public Nullable<int> ColorId { get; set; }
        public string VIN { get; set; }
        public Nullable<int> SegmentId { get; set; }
    }
}
