//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_type
    {
        public int Id { get; set; }
        public string type_name { get; set; }
        public Nullable<System.DateTime> DATE_OF_UPDATE { get; set; }
    }
}
