//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class discountcart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public discountcart()
        {
            this.payment_plan = new HashSet<payment_plan>();
        }
    
        public int Id { get; set; }
        public string type_name { get; set; }
        public string code { get; set; }
        public Nullable<bool> statu { get; set; }
        public string figure { get; set; }
        public Nullable<int> currency { get; set; }
        public Nullable<int> value { get; set; }
        public Nullable<int> Formula { get; set; }
        public Nullable<int> Ekleyen_Kullanici { get; set; }
        public Nullable<System.DateTime> DATE_OF_UPDATE { get; set; }
    
        public virtual CURRENCY CURRENCY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_plan> payment_plan { get; set; }
    }
}
