//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_INVOICE
    {
        public int ID { get; set; }
        public Nullable<int> senaryo_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> E_invoice_type_id { get; set; }
        public Nullable<int> odeme_yontemi_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string SATISKANALI { get; set; }
        public Nullable<int> CarDetail_ID { get; set; }
        public Nullable<int> MIKTAR { get; set; }
        public Nullable<decimal> BIRIM_FIYATI { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
        public Nullable<decimal> FATURA_TOPLAM { get; set; }
        public Nullable<decimal> TOPLAM_ISKONTO { get; set; }
        public Nullable<decimal> TOPLAM_KDV { get; set; }
        public Nullable<decimal> KDV_DAHIL_TOPLAM_TUTAR { get; set; }
        public Nullable<decimal> ODENECEK_TUTAR { get; set; }
        public Nullable<System.DateTime> DATE_OF_UPDATE { get; set; }
    }
}
