//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int Id { get; set; }
        public string action_table { get; set; }
        public string action_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> date_of { get; set; }
    }
}
