//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class medium
    {
        public int id { get; set; }
        public string image_name { get; set; }
        public string image_subtitle { get; set; }
        public string image_title { get; set; }
        public string image_path { get; set; }
    }
}
