//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_plan
    {
        public int Id { get; set; }
        public Nullable<int> code { get; set; }
        public string explanation { get; set; }
        public Nullable<int> discount_id { get; set; }
        public Nullable<bool> statu { get; set; }
        public Nullable<int> Ekleyen_Kullanici { get; set; }
        public Nullable<System.DateTime> DATE_OF_UPDATE { get; set; }
    }
}
