//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Post_id { get; set; }
        public Nullable<int> content_id { get; set; }
        public Nullable<int> users_id { get; set; }
        public Nullable<System.DateTime> Post_date { get; set; }
    }
}
