//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class userproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userproduct()
        {
            this.SOLD_PRODUCT = new HashSet<SOLD_PRODUCT>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> cardetail_id { get; set; }
        public Nullable<System.DateTime> date_of_created { get; set; }
        public Nullable<System.DateTime> date_of_updated { get; set; }
        public Nullable<bool> published_on { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<bool> isSaled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLD_PRODUCT> SOLD_PRODUCT { get; set; }
    }
}
